// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CustomSpriteSheet","status":true,"description":"Handles custom sprite sheet dimensions with spacing","parameters":{"frameWidth":"107","frameHeight":"283","paddingLeft":"25","spacingHorizontal":"90","spacingVertical":"70","framesPerRow":"8","totalRows":"8"}},
{"name":"PixelMovement","status":true,"description":"Enables smooth pixel-by-pixel movement instead of grid-based","parameters":{"enablePixelMovement":"true","pixelMoveSpeed":"4.0"}},
{"name":"EightDirectional","status":true,"description":"Enables 8-directional movement and sprite animations","parameters":{"enableDiagonalMovement":"true","diagonalSpeed":"0.71"}}
];
